// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-Q38uz_rEHecLdvLm-XelVDUPCoiO90',
    appId: '1:819214502545:web:01e901859bb95a6d9acd30',
    messagingSenderId: '819214502545',
    projectId: 'taleem-hub-831ec',
    authDomain: 'taleem-hub-831ec.firebaseapp.com',
    storageBucket: 'taleem-hub-831ec.firebasestorage.app',
    measurementId: 'G-6BKE77Z37D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpctiNVHEcJ0qMe_RxsARWAWb9hnhEQn4',
    appId: '1:819214502545:android:6a00595f147ea05d9acd30',
    messagingSenderId: '819214502545',
    projectId: 'taleem-hub-831ec',
    storageBucket: 'taleem-hub-831ec.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZDM6AbRLndVGjxvYBipY3Sl1A-tIzQnI',
    appId: '1:819214502545:ios:b2dd08ad41f60f7e9acd30',
    messagingSenderId: '819214502545',
    projectId: 'taleem-hub-831ec',
    storageBucket: 'taleem-hub-831ec.firebasestorage.app',
    iosBundleId: 'com.ahkstudios.taleemHub',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZDM6AbRLndVGjxvYBipY3Sl1A-tIzQnI',
    appId: '1:819214502545:ios:95b980bdee51b98a9acd30',
    messagingSenderId: '819214502545',
    projectId: 'taleem-hub-831ec',
    storageBucket: 'taleem-hub-831ec.firebasestorage.app',
    iosBundleId: 'com.schoolingsystem.schoolPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg-Q38uz_rEHecLdvLm-XelVDUPCoiO90',
    appId: '1:819214502545:web:3bd3c8d601c532399acd30',
    messagingSenderId: '819214502545',
    projectId: 'taleem-hub-831ec',
    authDomain: 'taleem-hub-831ec.firebaseapp.com',
    storageBucket: 'taleem-hub-831ec.firebasestorage.app',
    measurementId: 'G-F5K0X6LLBT',
  );
}
