"""promotion records

Revision ID: 0d8ce8e9a895
Revises: 11c374f5bc80
Create Date: 2026-07-04 17:10:57.315494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0d8ce8e9a895'
down_revision: Union[str, None] = '11c374f5bc80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_records',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('from_section_id', sa.UUID(), nullable=True),
    sa.Column('to_section_id', sa.UUID(), nullable=True),
    sa.Column('from_session_id', sa.UUID(), nullable=True),
    sa.Column('to_session_id', sa.UUID(), nullable=True),
    sa.Column('exam_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_session_id'], ['academic_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_session_id'], ['academic_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_records_school_id'), 'promotion_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_promotion_records_student_id'), 'promotion_records', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotion_records_student_id'), table_name='promotion_records')
    op.drop_index(op.f('ix_promotion_records_school_id'), table_name='promotion_records')
    op.drop_table('promotion_records')
    # ### end Alembic commands ###
