"""online classes

Revision ID: 30c1d0d19a1e
Revises: 3ad3e2eb04bd
Create Date: 2026-06-18 02:47:50.285374
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30c1d0d19a1e'
down_revision: Union[str, None] = '3ad3e2eb04bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('online_classes',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_online_classes_school_id'), 'online_classes', ['school_id'], unique=False)
    op.create_index(op.f('ix_online_classes_section_id'), 'online_classes', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_online_classes_section_id'), table_name='online_classes')
    op.drop_index(op.f('ix_online_classes_school_id'), table_name='online_classes')
    op.drop_table('online_classes')
    # ### end Alembic commands ###
