"""homework: submission seen_at

Revision ID: 411ef2731df4
Revises: 7b9ad02ebed2
Create Date: 2026-07-28 17:33:28.744119
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '411ef2731df4'
down_revision: Union[str, None] = '7b9ad02ebed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'seen_at')
    # ### end Alembic commands ###
