"""examination

Revision ID: 536fa75679ea
Revises: f4fcc8f5a4ea
Create Date: 2026-06-18 01:35:57.649597
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '536fa75679ea'
down_revision: Union[str, None] = 'f4fcc8f5a4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_class_id'), 'exams', ['class_id'], unique=False)
    op.create_index(op.f('ix_exams_school_id'), 'exams', ['school_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('max_total', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_result_exam_student')
    )
    op.create_index(op.f('ix_exam_results_exam_id'), 'exam_results', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_results_school_id'), 'exam_results', ['school_id'], unique=False)
    op.create_index(op.f('ix_exam_results_student_id'), 'exam_results', ['student_id'], unique=False)
    op.create_table('exam_subjects',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('pass_marks', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'subject_id', name='uq_exam_subject')
    )
    op.create_index(op.f('ix_exam_subjects_exam_id'), 'exam_subjects', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_subjects_school_id'), 'exam_subjects', ['school_id'], unique=False)
    op.create_table('marks',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('exam_subject_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('marked_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_subject_id', 'student_id', name='uq_mark_paper_student')
    )
    op.create_index(op.f('ix_marks_exam_subject_id'), 'marks', ['exam_subject_id'], unique=False)
    op.create_index(op.f('ix_marks_school_id'), 'marks', ['school_id'], unique=False)
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marks_student_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_school_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_exam_subject_id'), table_name='marks')
    op.drop_table('marks')
    op.drop_index(op.f('ix_exam_subjects_school_id'), table_name='exam_subjects')
    op.drop_index(op.f('ix_exam_subjects_exam_id'), table_name='exam_subjects')
    op.drop_table('exam_subjects')
    op.drop_index(op.f('ix_exam_results_student_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_school_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_exam_id'), table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_exams_school_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_class_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
