"""academic structure

Revision ID: 575e6b65ce1f
Revises: defccc11566f
Create Date: 2026-06-18 00:46:29.543739
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '575e6b65ce1f'
down_revision: Union[str, None] = 'defccc11566f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'session_id', 'name', name='uq_class_school_session_name')
    )
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_table('sections',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('class_teacher_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'name', name='uq_section_class_name')
    )
    op.create_index(op.f('ix_sections_class_id'), 'sections', ['class_id'], unique=False)
    op.create_index(op.f('ix_sections_school_id'), 'sections', ['school_id'], unique=False)
    op.create_table('subjects',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_subject_school_code')
    )
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.create_table('timetable_slots',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_slots_school_id'), 'timetable_slots', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_section_id'), 'timetable_slots', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_slots_section_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_school_id'), table_name='timetable_slots')
    op.drop_table('timetable_slots')
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_sections_school_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_class_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
