"""leave: add student_id

Revision ID: 7b9ad02ebed2
Revises: d550f6fcada1
Create Date: 2026-07-28 04:25:36.532667
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b9ad02ebed2'
down_revision: Union[str, None] = 'd550f6fcada1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('student_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_leave_requests_student_id'), 'leave_requests', ['student_id'], unique=False)
    op.create_foreign_key(None, 'leave_requests', 'users', ['student_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The foreign key was created unnamed; dropping the column drops it too.
    op.drop_index(op.f('ix_leave_requests_student_id'), table_name='leave_requests')
    op.drop_column('leave_requests', 'student_id')
    # ### end Alembic commands ###
