"""hostel

Revision ID: 83fa49553d55
Revises: b56dc41ef47d
Create Date: 2026-06-18 02:37:15.704720
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '83fa49553d55'
down_revision: Union[str, None] = 'b56dc41ef47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostel_blocks',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('warden_name', sa.String(length=150), nullable=True),
    sa.Column('warden_phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_hostel_block_school_name')
    )
    op.create_index(op.f('ix_hostel_blocks_school_id'), 'hostel_blocks', ['school_id'], unique=False)
    op.create_table('hostel_rooms',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('room_no', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupied', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['hostel_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'room_no', name='uq_hostel_room_block_no')
    )
    op.create_index(op.f('ix_hostel_rooms_block_id'), 'hostel_rooms', ['block_id'], unique=False)
    op.create_index(op.f('ix_hostel_rooms_school_id'), 'hostel_rooms', ['school_id'], unique=False)
    op.create_table('hostel_allocations',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('allocated_on', sa.Date(), nullable=False),
    sa.Column('vacated_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['hostel_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_allocations_room_id'), 'hostel_allocations', ['room_id'], unique=False)
    op.create_index(op.f('ix_hostel_allocations_school_id'), 'hostel_allocations', ['school_id'], unique=False)
    op.create_index(op.f('ix_hostel_allocations_student_id'), 'hostel_allocations', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hostel_allocations_student_id'), table_name='hostel_allocations')
    op.drop_index(op.f('ix_hostel_allocations_school_id'), table_name='hostel_allocations')
    op.drop_index(op.f('ix_hostel_allocations_room_id'), table_name='hostel_allocations')
    op.drop_table('hostel_allocations')
    op.drop_index(op.f('ix_hostel_rooms_school_id'), table_name='hostel_rooms')
    op.drop_index(op.f('ix_hostel_rooms_block_id'), table_name='hostel_rooms')
    op.drop_table('hostel_rooms')
    op.drop_index(op.f('ix_hostel_blocks_school_id'), table_name='hostel_blocks')
    op.drop_table('hostel_blocks')
    # ### end Alembic commands ###
