"""calendar events

Revision ID: 953786a4aef6
Revises: 0d8ce8e9a895
Create Date: 2026-07-04 17:35:14.569295
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '953786a4aef6'
down_revision: Union[str, None] = '0d8ce8e9a895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_event_type'), 'calendar_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_calendar_events_school_id'), 'calendar_events', ['school_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_date'), 'calendar_events', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_events_start_date'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_school_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_event_type'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
