"""transport

Revision ID: b56dc41ef47d
Revises: 5454b2fdef36
Create Date: 2026-06-18 02:32:39.762039
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b56dc41ef47d'
down_revision: Union[str, None] = '5454b2fdef36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('registration_no', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=150), nullable=True),
    sa.Column('driver_phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'registration_no', name='uq_vehicle_school_reg')
    )
    op.create_index(op.f('ix_vehicles_school_id'), 'vehicles', ['school_id'], unique=False)
    op.create_table('routes',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_school_id'), 'routes', ['school_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('pickup_time', sa.Time(), nullable=True),
    sa.Column('dropoff_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_stops_school_id'), 'route_stops', ['school_id'], unique=False)
    op.create_table('transport_assignments',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('stop_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['route_stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', name='uq_transport_student')
    )
    op.create_index(op.f('ix_transport_assignments_route_id'), 'transport_assignments', ['route_id'], unique=False)
    op.create_index(op.f('ix_transport_assignments_school_id'), 'transport_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_transport_assignments_student_id'), 'transport_assignments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transport_assignments_student_id'), table_name='transport_assignments')
    op.drop_index(op.f('ix_transport_assignments_school_id'), table_name='transport_assignments')
    op.drop_index(op.f('ix_transport_assignments_route_id'), table_name='transport_assignments')
    op.drop_table('transport_assignments')
    op.drop_index(op.f('ix_route_stops_school_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_routes_school_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_vehicles_school_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
