"""exam seats

Revision ID: c39f0462080e
Revises: 953786a4aef6
Create Date: 2026-07-04 17:40:36.919855
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c39f0462080e'
down_revision: Union[str, None] = '953786a4aef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_seats',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('seat_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'room', 'seat_no', name='uq_seat_exam_room_seat'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_seat_exam_student')
    )
    op.create_index(op.f('ix_exam_seats_exam_id'), 'exam_seats', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_seats_school_id'), 'exam_seats', ['school_id'], unique=False)
    op.create_index(op.f('ix_exam_seats_student_id'), 'exam_seats', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_seats_student_id'), table_name='exam_seats')
    op.drop_index(op.f('ix_exam_seats_school_id'), table_name='exam_seats')
    op.drop_index(op.f('ix_exam_seats_exam_id'), table_name='exam_seats')
    op.drop_table('exam_seats')
    # ### end Alembic commands ###
